kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    receivers:
    - name: 'pagerduty'
      pagerduty_configs:
      - send_resolved: true
        service_key: 'https://events.pagerduty.com/integration/df95ac26588e4eaaa3b13c050dcff618/enqueue'
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'pagerduty'
      routes:
      - match:
          severity: critical
        receiver: 'pagerduty'
